# Site settings
title: Roger Luo
description: Research Assistant@UWaterloo
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Roger Luo
user_title: Research Assistant, UWaterloo
email: hiroger@qq.com
twitter_username: rogerluorl18
github_username:  Roger-luo
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
